image: docker:stable
services:
  - docker:dind

stages:
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  SSH_USER: yrosygwy
  SSH_HOST: 94.176.182.67

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY_BASE64" | base64 -d > /tmp/ssh_private_key
    - chmod 400 /tmp/ssh_private_key
    - ssh-keyscan -p 2224 -H 94.176.182.67 >> ~/.ssh/known_hosts # Add the SSH host key
    - |
      ssh -o StrictHostKeyChecking=no -i /tmp/ssh_private_key $SSH_USER@$SSH_HOST << 'EOF'
        cd /home/deployer/hms
        git pull origin main && inv update && inv restart
      EOF
  only:
    - main
  tags:
    - movo
  

deploy_prod:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - mkdir -p /movo
    - echo "$SSH_KEY_BASE64" | base64 -d > /movo/ssh_private_key
    - chmod 400 /movo/ssh_private_key
    - ssh-keyscan -p 2224 -H 94.176.182.67 >> ~/.ssh/known_hosts
    - ssh -o StrictHostKeyChecking=no -i /movo/ssh_private_key -p 2224 $SSH_USER@$SSH_HOST 'cd /home/yrosygwy/hms && git pull origin main && inv update && inv restart'
  only:
    - prod
  tags:
    - movo
